"""empty message

Revision ID: 7cbbf6012e79
Revises: ec0a9092b33c
Create Date: 2020-02-07 17:17:19.899687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cbbf6012e79'
down_revision = 'ec0a9092b33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero', 'share_phone',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index('latitude', table_name='incident')
    op.drop_index('longitude', table_name='incident')
    op.alter_column('user', 'share_phone',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'share_phone',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.create_index('longitude', 'incident', ['longitude'], unique=True)
    op.create_index('latitude', 'incident', ['latitude'], unique=True)
    op.alter_column('hero', 'share_phone',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
