"""empty message

Revision ID: ec0a9092b33c
Revises: 26cebab824c3
Create Date: 2020-02-01 03:20:49.913278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0a9092b33c'
down_revision = '26cebab824c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('longitude', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'incident', ['longitude'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='unique')
    op.drop_column('incident', 'longitude')
    # ### end Alembic commands ###
